CREATE TABLE mentoras (
  id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  slug                TEXT UNIQUE NOT NULL,
  dominio_custom      TEXT UNIQUE,
  dominio_dns_registros JSONB NOT NULL DEFAULT '[]'::jsonb,
  dominio_verificado  BOOLEAN NOT NULL DEFAULT FALSE,
  nome                TEXT NOT NULL,
  email               TEXT NOT NULL,
  titulo              TEXT NOT NULL DEFAULT 'Descubra sua Personalidade',
  subtitulo           TEXT NOT NULL DEFAULT 'Um questionário científico de 120 perguntas baseado no modelo Big Five.',
  logo_principal_url  TEXT,
  logo_secundaria_url TEXT,
  logo_icone_url      TEXT,
  cor_primaria        TEXT NOT NULL DEFAULT '#C99A2D',
  cor_fundo           TEXT NOT NULL DEFAULT '#FAF7F2',
  cor_texto           TEXT NOT NULL DEFAULT '#2C2820',
  texto_botao         TEXT NOT NULL DEFAULT 'Iniciar teste',
  foto_circular       BOOLEAN NOT NULL DEFAULT FALSE,
  perguntas_extras    JSONB NOT NULL DEFAULT '[]'::jsonb,
  opcoes_resposta     JSONB NOT NULL DEFAULT '["Discordo totalmente","Discordo","Neutro","Concordo","Concordo totalmente"]'::jsonb,
  titulo_obrigado     TEXT NOT NULL DEFAULT 'Obrigado!',
  texto_obrigado      TEXT NOT NULL DEFAULT 'Suas respostas foram enviadas. Você receberá a análise em breve.',
  openai_api_key      TEXT,
  prompt_extra        TEXT,
  modelo_ia           TEXT NOT NULL DEFAULT 'gpt-4o-mini',
  vector_store_id     TEXT,
  knowledge_file_id   TEXT,
  ativo               BOOLEAN NOT NULL DEFAULT TRUE,
  criado_em           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  atualizado_em       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
